README.md
Fix Failover Sample App
Fix Failover Sample App
RDS-241
@sergiyvamz 
@seneramz 
@hsuamz
=> Fix Failover Sample App

build.gradle.kts, docker/docker-compose.yml, gradle.properties, src/main/user-impl/java/com/mysql/cj/jdbc/Driver.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java, src/test/java/com/mysql/cj/jdbc/NonRegisteringDriverTest.java, src/test/java/com/mysql/cj/jdbc/ha/ca/AuroraTopologyServiceTest.java, src/test/java/testsuite/BaseTestCase.java, src/test/java/testsuite/failover/ReplicationFailoverIntegrationTest.java, src/test/java/testsuite/regression/CachedRowsetTest.java, src/test/java/testsuite/regression/ConnectionRegressionTest.java, src/test/java/testsuite/regression/ResultSetRegressionTest.java, src/test/java/testsuite/simple/ConnectionTest.java
Handle IllegalStateException
- handle IllegalStateException
- disable registration of community driver
RDS-262
@seneramz 
@sergiyvamz 
@hsuamz
=> Handle IllegalStateException

README.md, src/test/java/testsuite/simple/ConnectionTest.java
Changed README to improve clarify clusterInstanceHostPattern parameter. 
Updated Readme
RDS264
@hsuamz 
@sergiyvamz 
@congoamz 
@seneramz
=> Added clarifications to clusterHostInstance

src/test/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxyTest.java
Correcting minor unit test issues
- Some small logic corrections as well as removal of unnecessary logic
N/A
@seneramz 
@hsuamz 
@sergiyvamz
=> Correcting minor unit test issues

README.md
The following README changes are intended to provide clarity and examples of how to consume the driver.
In addition, the driver name is now made clear in the documentation.
=> Clarifying Installation Instructions and Driver Name

build.gradle.kts
Include THIRD-PARTY-LICENSES in Driver jar
Include THIRD-PARTY-LICENSES in Driver jar
N/A
@seneramz 
@sergiyvamz 
@hsuamz
=> Include THIRD-PARTY-LICENSES in Driver jar

README.md
Fix minor README issues
Fix minor README issues
@seneramz 
@sergiyvamz 
@samathaamz 
@hsuamz
=> Fix minor README issues

src/test/java/testsuite/failover/FailoverIntegrationTest.java
Integration test 1.2 initiates failover on Statement invocation
- previously failover was initiated on a Connection invocation, which is the purpose of test 1.1. The purpose of this test is instead to failover on a JdbcInterfaceProxy invocation (eg a Statement object invocation)
@seneramz 
@faviansamatha 
@hsuamz
=> Integration test 1.2 initiates failover on Statement invocation

src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
Address spotbugs errors by adding consistent synchronization in proxy class.
=> Add consistent synchronization

CHANGES, README.md, gradle.properties
Changed version from 0.1.0 to 1.0.0
- Updated README.md
- Updated Changelog
- Updated Version number
@hsuamz 
@congoamz 
@seneramz
=> Change to version 1.0.0

README.md, docs/index.html
This reverts commit 92862fba536c663b71b517a9b9169704c0f75f0a.
I'm reverting the html file - it looks like the editor swapped in some sort of template that made a mess of the IO page.  It will be easiest to revert and redo...
=> Revert "Tweaked MySQL IO page content (#120)"

docs/index.html
Re-updated IO page
Minor grammar changes to the IO page; the first check in wiped out formatting, but this uploaded copy preserves the old formatting.
=> Updated index.html (the MySQL IO page)

README.md
Cleaned up README.md file
Cleaned up README.md file for MySQL driver.
=> Tweaked README.md to clean up table formatting, minor grammar/spelling

src/demo/java/customplugins/README.md
Tweaked wording a bit in connection plugin example.
=> Fine-tuned readme.md for connection plugin example

README.md
This update to the README.md file updates mentions of version 0.4.0 to 1.0.0 and removes the 'preview' warning from the file.  DO NOT MERGE IT UNTIL WE GA.
Signed-off-by: susanmdouglas <susandou@amazon.com>
This update to the README.md file updates mentions of version 0.4.0 to 1.0.0 and removes the 'preview' warning from the file.  DO NOT MERGE IT UNTIL WE GA.
This update to the README.md file updates mentions of version 0.4.0 to 1.0.0 and removes the 'preview' warning from the file.  DO NOT MERGE IT UNTIL WE GA.
=> DO NOT MERGE UNTIL RELEASE DAY 1.0.0 - README.md file version/preview update

.github/workflows/release_draft.yml, build.gradle.kts
Remove mentions of Public Preview
Remove mentions of Public Preview from Maven publishes & workflows for GitHub draft/release
@hsuamz @sergiyvamz
=> chore: Remove mentions of Public Preview

README.md, build.gradle.kts, src/main/protocol-impl/java/com/mysql/cj/protocol/a/NativeAuthenticationProvider.java, src/main/protocol-impl/java/com/mysql/cj/protocol/a/authentication/AwsIamAuthenticationTokenHelper.java, src/test/java/testsuite/integration/container/AuroraMysqlFailoverIntegrationTest.java, src/test/java/testsuite/integration/container/AuroraMysqlIntegrationBaseTest.java, src/test/java/testsuite/integration/container/ReplicationFailoverIntegrationTest.java, src/test/java/testsuite/integration/utility/AuroraTestUtility.java, src/test/java/testsuite/integration/utility/ContainerHelper.java
Upgrade to AWS SDK v.2.17.165 
@ColinKYuen 
@hsuamz
=> upgrade to AWS SDK v.2.17.165

src/main/core-api/java/com/mysql/cj/util/ExpiringCache.java
Fix concurrency issues with Aurora topology cache. The issue has been mentioned in 
https://github.com/awslabs/aws-mysql-jdbc/discussions/188
@ColinKYuen 
@karenc-bq 
@hsuamz
=> fix concurrency issues with topology cache

.github/workflows/maven_snapshot.yml, build.gradle.kts, gradle.properties
Build and upload snapshot builds
@hsuamz 
@ColinKYuen
=> add snapshot builds

build.gradle.kts
Automatically increment patch version for snapshot builds
@hsuamz 
@ColinKYuen
=> increment subminor version for snapshot builds

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java, src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java
Fix incorrect initial connection properties reported by #191 
Failover connection plugin was using `PropertySet#exposeAsProperties` to retrieve the initial connection properties. This method returns all runtime modifiable properties regardless of whether users have explicitly set them during connection. In cases where the properties were not explicitly set, predefined values were used.
When creating new connections with the initial connection properties these default values would be passed to the connection, overriding the values set in the server.
@sergiyvamz
=> fix: incorrect initial connection properties

README.md
Update README to include snapshot builds, add note about secrets manager plugin dependencies.
- Added section to README on how to use snapshot builds.
- Added note about additional required dependencies when using the Secrets Manager plugin.
=> Update README to include snapshot builds

CHANGELOG.md, README.md, gradle.properties
- Updated driver version for the 1.1.0 release.
- Driver version updated in `gradle.properties` and `README.md`.
- Updated `CHANGELOG.md` for the release.
=> chore: update driver version for 1.1.0 release

.github/ISSUE_TEMPLATE/bug_report.yml
fix bug_report.yml syntax errors
@sergiyvamz
=> chore: fix bug_report.yml syntax errors

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/DefaultMonitorService.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/Monitor.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/MonitorConnectionContext.java
Fix the issue https://github.com/awslabs/aws-mysql-jdbc/issues/254
- Check if monitor still exists before removing monitoring context
- Invalidate monitoring context earlier 
@karenc-bq
=> fix issue while stopping monitoring context

README.md
The example URL template for DBeaver is wrong
=> Correct DBeaver template URL

README.md, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ConnectionMethodAnalyzer.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ITransactionStateMachine.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ReadWriteSplittingPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ReadWriteSplittingStateMachine.java, src/test/java/com/mysql/cj/jdbc/ha/plugins/ReadWriteSplittingPluginTest.java
Add documentation for the read-write splitting plugin
@karenc-bq
=> Add documentation for the read-write splitting plugin

CHANGELOG.md, README.md, gradle.properties
- Updated driver version for the 1.1.1 release.
- Driver version updated in `gradle.properties` and `README.md`.
- Updated `CHANGELOG.md` for the release.
=> chore: update driver version for 1.1.1 release

README.md
Fix plugin factory package names in documentation. https://github.com/awslabs/aws-mysql-jdbc/issues/293
@karenc-bq 
@congoamz 
@hsuamz
=> fix plugin factories package names

src/main/core-api/java/com/mysql/cj/conf/ConnectionUrl.java, src/test/java/testsuite/integration/container/AuroraMysqlIntegrationTest.java
Fix issue https://github.com/awslabs/aws-mysql-jdbc/issues/264
@karenc-bq
=> fix issue #264

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPlugin.java
Check if trace logging is enabled to avoid unnecessary String formatting
=> Check if trace logging is enabled to avoid unnecessary String formatting

CHANGELOG.md, README.md, gradle.properties
Updated driver version for the 1.1.2 release.
- Driver version updated in gradle.properties and README.md.
- Updated CHANGELOG.md for the release.
@sergiyvamz 
@hsuamz 
@aaron-congo
=> chore: update the driver version for 1.1.2 release

build.gradle.kts
build: add shading to -sources.jar to reflect the main jar which is shaded (#304)
NOTE: marked as WIP since I've yet to finish all the testing. Creating it for early feedback.
Currently, the sources JAR is not shaded, but the main JAR is. This makes it difficult for users that are debugging using the source files in their IDEs. The purpose of this PR is to address that by shading the sources JAR as well so that they match the main JAR. 
The Gradle shadow plugin does not support shading the sources JAR. So a custom solution was instead made.
Changes:
- Added a new Gradle task `shadeSourcesJar` to shade the sources JAR
- Made the `assemble` task depend on the `shadeSourcesJar` task
- Replaced the `sourcesJar` task artifacts in the Maven publication with the `shadeSourcesJar` task artifacts …
=> build: add shading to -sources.jar to reflect the main jar which is shaded (#304)

CHANGELOG.md, README.md, build.gradle.kts, gradle.properties
Update version from 1.1.2 to 1.1.3
=> Update version from 1.1.2 to 1.1.3

.github/pull_request_template.md
=> Adding to the PR Template

.github/pull_request_template.md
Reverts awslabs/aws-mysql-jdbc#338
=> Revert "Adding to the PR Template"

.github/workflows/main.yml
increase session token expiration time
@karenc-bq
=> increase session token expiration time

README.md
Incorporate changes and addresses reviews from PR #266
=> docs: update DBeaver documentation

README.md
@sergiyv-improving @karenc-bq @aaron-congo @joyc-bq @brunos-bq
=> doc: update documentation to reflect that driver does not support blue/green deployments

README.md
=> docs: add messaging around monthly release cadence

README.md, gradle.properties
=> chore: update version from 1.1.4 to 1.1.5

README.md
=> docs: add list of database engine versions tested against

build.gradle.kts
=> Remove SampleApplication from distribution jar

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyService.java, src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyServiceTest.java
=> fix: Use fallback LastUpdated timestamp when topology query returns invalid timestamp (ex. daylight savings)

CHANGELOG.md
=> add issue 386 / daylight saving to changelog 1.1.6

CHANGELOG.md, README.md, gradle.properties
=> chore: update versioning and changelog for 1.1.8

README.md
Add a sample connection string on how to configure a standard logger
=> docs: add example to configure a logger

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java, src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java
Keep currentHostIndex and hosts list in sync and pick new connection when host role changes
When picking a new connection, the failover plugin should use the latest topology if it is available. A check was also added to ensure that when the topology is updated, if the current host changes to a reader, a new connection is picked.
Addresses #303.
@albanf
=> fix: keep currentHostIndex and hosts list in sync and pick new connection when host role changes

CHANGELOG.md, README.md, RELEASE_POLICY.md, gradle.properties
=> chore: update changelog and versioning for 1.1.9

CHANGELOG.md, README.md, RELEASE_POLICY.md, gradle.properties
Update changelog and versioning for 1.1.10
=> chore: update changelog and versioning for 1.1.10

README.md, RELEASE_POLICY.md
Update known limitations with global databases
- Update known limitations with global databases
- Add release/maintenance policy links to the known limitations and releases sections on the README
=> docs: update known limitations with global databases

CHANGELOG.md, README.md, RELEASE_POLICY.md, gradle.properties
=> chore: update changelog and versioning for 1.1.11 release

.github/workflows/performance.yml
Add performance tests workflow
@karenc-bq
=> add performance tests workflow

.github/workflows/performance.yml
- Upgrade actions
- Increase AWS STS token expiration
@karenc-bq
=> Upgrade performance workflow

README.md, build.gradle.kts, src/main/core-api/java/com/mysql/cj/conf/PropertyDefinitions.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/efm2/DefaultMonitorService.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/efm2/IMonitor.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/efm2/IMonitorInitializer.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/efm2/IMonitorService.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/efm2/Monitor.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/efm2/MonitorConnectionContext.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/efm2/NodeMonitoringConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/efm2/NodeMonitoringConnectionPluginFactory.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/util/SlidingExpirationCache.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/util/SlidingExpirationCacheWithCleanupThread.java, src/test/java/testsuite/integration/container/AuroraMysqlPerformanceForEfm2IntegrationTest.java, src/test/java/testsuite/integration/container/AuroraMysqlPerformanceIntegrationTest.java
Enhanced host monitoring plugin ver.2 (redesign)
=> Enhanced host monitoring plugin ver.2 (redesign)

CHANGELOG.md, README.md, RELEASE_POLICY.md, gradle.properties
chore: update changelog and versioning for 1.1.12 release
chore: update changelog and versioning for 1.1.12 release
=> chore: update changelog and versioning for 1.1.12 release

CHANGELOG.md, README.md, RELEASE_POLICY.md, gradle.properties
=> chore: update changelog and versioning for 1.1.13 release

.github/pull_request_template.md, .github/workflows/main.yml
- fix failing workflows caused by duplicated artifact name
- add license to PR template
=> chore: update workflow and PR template

src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java, src/main/user-impl/java/com/mysql/cj/jdbc/ha/util/RdsUtils.java, src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java, src/test/java/com/mysql/cj/util/RdsUtilsTests.java
MySQL - Update China endpoint patterns
Refactored parsing logic to be centralized in RdsUtils. Updated functions and regex patterns to support Chinese endpoints. Added unit tests for testing endpoint regex.
=> chore: MySQL China endpoints

src/main/core-api/java/com/mysql/cj/util/Util.java
Fix missing log message argument
Refactored function to pass failing argument into exception, making the log message clearer
=> fix: log message

src/test/java/testsuite/integration/container/AuroraMysqlIntegrationBaseTest.java, src/test/java/testsuite/integration/container/HikariCPIntegrationTest.java
Allow fetch topology retries for HikariCP integration tests
=> test: refactor HikariCP integration tests to be more stable

.github/workflows/main.yml, .github/workflows/maven_release.yml, .github/workflows/maven_snapshot.yml, .github/workflows/performance.yml, .github/workflows/release_draft.yml
GitHub actions scripts updated to latest
Update actions versions due to deprecation warnings in builds
=> chore: update GitHub Actions

.github/workflows/maven_release.yml, .github/workflows/maven_snapshot.yml, .github/workflows/release_draft.yml
fix for failing maven action
add distribution to actions
=> fix: add distribution to github actions

CHANGELOG.md, README.md, RELEASE_POLICY.md, gradle.properties
=> chore: update changelog and versioning for 1.1.14 release

CHANGELOG.md, README.md, RELEASE_POLICY.md, gradle.properties
version bump and changelog update for 1.1.15
version bump and changelog update for 1.1.15
=> version bump and changelog update for 1.1.15
