awslabs/aws-mysql-jdbc

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandler.java
- src/test/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandlerTest.java
Reader failover improvements
During a reader failover process, driver may not be able to connect to any reader node. Driver raises an exception 08001 ("Unable to connect") in this case. Improvement includes making reader failover handler to repeat attempts until successfully connect to a reader, or until process exceeds allowed time. 
RDS-274
@congoamz 
@seneramz 
@hsuamz
> Reader failover improvements

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandler.java
- src/test/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandlerTest.java
Driver's unable to make a reader connection.
When cluster has 2 node configuration and driver is connected to a reader, driver couldn't reconnect to new reader in case of cluster failover.
RDS-355
@congoamz 
@hsuamz 
@seneramz
> loop until successful

- src/test/java/testsuite/failover/FailoverIntegrationTest.java
- src/test/java/testsuite/regression/CachedRowsetTest.java
- src/test/java/testsuite/regression/ResultSetRegressionTest.java
Improve integration tests timeouts
Use sockets blocking communication to db cluster instances instead of repeatedly running fault injection SQL.
RDS-381
@congoamz 
@samathaamz 
@seneramz 
@hsuamz
> Improve integration tests timeouts

- .github/pull_request_template.md
- src/main/core-api/java/com/mysql/cj/util/Util.java
- src/main/resources/com/mysql/cj/LocalizedErrorMessages.properties
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/AuroraTopologyService.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareConnectionProxy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandler.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareUtils.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareWriterFailoverHandler.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/TopologyService.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/WriterFailoverHandler.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/WriterFailoverResult.java
- src/test/java/com/mysql/cj/jdbc/ha/ca/AuroraTopologyServiceTest.java
- src/test/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareReaderFailoverHandlerTest.java
- src/test/java/testsuite/failover/FailoverIntegrationTest.java
Handle topology queries that don't return a writer
- also added guards against exceptions that might arise from calling this.hosts.get when this.hosts is null or empty, or this.hosts.get(this.currentHostIndex) when this.currentHostIndex == -1
- reader failover, writer failover, ClusterAwareReaderFailover#getReaderConnection, and AuroraTopologyService#getTopology never return null
@seneramz 
@hsuamz 
@samathaamz
> Handle topology queries that don't return a writer

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareUtils.java
- src/test/java/com/mysql/cj/jdbc/SQLXMLTests.java
- src/test/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareTestUtils.java
- src/test/java/testsuite/failover/ReplicationFailoverIntegrationTest.java
Various files created by AWS had missing license headers. This PR corrects these attributions for these files.
License headers added for the following files:
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareUtils.java
- src/test/java/com/mysql/cj/jdbc/SQLXMLTests.java 
- src/test/java/com/mysql/cj/jdbc/ha/ca/ClusterAwareTestUtils.java
- src/test/java/testsuite/failover/ReplicationFailoverIntegrationTest.java
@hsuamz 
@sergiyvamz 
@congoamz 
@seneramz
> Added missing license headers

- README.md
Update gradle dependency configuration in readme - compile configuration is deprecated
@hsuamz
> Update gradle dependency configuration in readme - compile configuration is deprecated

- README.md
- build.gradle.kts
- src/main/resources/META-INF/services/java.sql.Driver
- src/main/user-impl/java/software/aws/rds/jdbc/mysql/Driver.java
Fix source and target Java level not set to 8
- Set the `sourceCompatibility` and the `targetCompatibility` values to Java 1.8 so project compiles to Java 8.
- Remove `you can also use 'software.aws.rds.jdbc.mysql.Driver()' to register`, this line is only printed when the driver has been registered.
- Remove `implements Driver` since `NonRegisteringDriver` already implements it.
@hsuamz 
@congoamz
> fix: Fix source and target Java level not set to 8

- build.gradle.kts
- src/main/resources/META-INF/services/java.sql.Driver
- src/test/java/testsuite/regression/ConnectionRegressionTest.java
Fix hanging test `testBug73053` and failing test `testBug69579`
The `META-INF/services/java.sql.Driver` file allows the `DriverManager` to locate and register a JDBC 4.0 driver. When this file is hard coded to the repository instead of manually generating this file, whenever `DriverManager.getConnection()` is called in the test, the AWS driver will also be registered. This interfered with `testBug69579`.
`testBug73053` hangs on Github Actions when it attempts to close the test connection, but passes locally. This is because the remote environment uses `TLSv1.3`.
When closing a connection, if `TLSv1.3` is used, the driver roughly follows this workflow: 
```
SSLSocketImpl#duplexCloseOutput -> SSLSocketImpl#bruteForceCloseInput(false) -> SSLSocketInputRecord#deplete
```
and it gets stuck in …
> Fix broken tests

- .github/workflows/maven_release.yml
- .github/workflows/release_draft.yml
- CHANGELOG.md
- README.md
- build.gradle.kts
- gradle.properties
Automate Maven Release
GitHub Actions `maven_release` automatically builds and signs drivers which are then uploaded to **Maven Staging**.
The following workflow runs whenever a **new release on GitHub is published.**
* Build Driver
* Set-up GPG to be used for signing
* Publishes signed files to Maven
Once published, it will be in the Staging Repository where you can manually **close** then later **release**.
The following secrets are required for new workflow
* `GPG_KEY_ID`, the public key ID (Last 8 characters)
* `MAVEN_USERNAME`, Login Username to Nexus Repository Manager
* `MAVEN_USERNAME`, Login Password to Nexus Repository Manager
Updated CHANGELOG.md, README.md, versioning to reflect changes.
> chore: Automate Maven Release

- README.md
Documentation review and changes for the upcoming 0.4.0 release.
- Reviewed `Connection Plugin Manager` and `Enhanced Failure Monitoring` sections.
- Updated wording for the general README.
> docs: Reviewed and tweaked wording in README.md

- README.md
- src/demo/java/customplugins/ExecutionTimeConnectionPlugin.java
Updating README
- Updated `ExecutionTimeConnectionPlugin` javadocs to match updated `Custom Connection/README.md`
- Clarified Enhanced Failure Monitoring as a plugin in `README.md` 
@karenc-bq @hsuamz
> docs: Updating README.md

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
fix: filter out methods that don't require failover
address issue reported in #206 
Execute `abort`, `close` and `isClosed` directly without the failover functionality.
@sergiyvamz
> fix: filter out methods that don't require failover

- src/main/core-impl/java/com/mysql/cj/log/BaseMetricsHolder.java
Fix off by one error in performance histogram
There was an off by one error causing query times to be listed in the wrong category of the performance histogram.
> Fix off by one error in performance histogram

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/RdsHostUtils.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ReadWriteSplittingPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/ReadWriteSplittingPluginTest.java
Add topology detection to the ReadWriteSplittingPlugin
- if a single host is supplied in the connection URL, attempt to query
Aurora to establish topology information
- if multiple hosts are supplied, simply use the supplied hosts for
topology information; the plugin will not query for topology
@karenc-bq
> Add topology detection to the ReadWriteSplittingPlugin

- src/main/core-impl/java/com/mysql/cj/conf/url/AwsMultiHostConnectionUrl.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/RdsHost.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/RdsHostUtils.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/RdsUrlType.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ReadWriteSplittingPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ReadWriteSplittingPluginFactory.java
- src/test/java/com/mysql/cj/jdbc/ha/ConnectionProxyTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/ReadWriteSplittingPluginTest.java
Implement compatibility with the FailoverConnectionPlugin
- ReadWriteSplittingPlugin checks for topology changes on SQLExceptions
- The reader connection or writer connection is updated to point to the
new connection after failover
- ConnectionProxy#setCurrentConnection no longer closes connections, so that the ReadWriteSplittingPlugin can quickly switch between the writer/reader connection without having to repeatedly open new connections
@karenc-bq 
@sergiyv-bitquill
> Implement compatibility with the FailoverConnectionPlugin

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/AutoCommitOffTransactionBoundaryState.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/AutoCommitOnTransactionBoundaryState.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/AutoCommitOnTransactionState.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ConnectionMethodAnalyzer.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ExceptionAnalyzer.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPluginFactory.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPluginTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java
- src/test/java/testsuite/integration/container/standard/StandardMysqlReadWriteSplittingTest.java
Fix bug where EFM plugin was swallowing a communications exception
- Connections are automatically closed when communications exceptions
occur, so the EFM plugin should throw them when encountered.
Otherwise, the invoked method will continue down the plugin chain and
execute against a closed connection. This can lead to a 'No
operations allowed after connection closed' exception
@karenc-bq
> Fix bug where EFM plugin was swallowing a communications exception

- src/test/java/testsuite/integration/container/aurora/AuroraMysqlFailoverIntegrationTest.java
- src/test/java/testsuite/integration/container/aurora/AuroraMysqlHardFailureIntegrationTest.java
- src/test/java/testsuite/integration/container/aurora/AuroraMysqlIntegrationBaseTest.java
- src/test/java/testsuite/integration/container/aurora/AuroraMysqlReadWriteSplittingTest.java
- src/test/java/testsuite/integration/container/aurora/HikariCPIntegrationTest.java
- src/test/java/testsuite/integration/container/aurora/HikariCPReadWriteSplittingTest.java
- src/test/java/testsuite/integration/container/aurora/IntegrationTestSuite.java
- src/test/java/testsuite/integration/container/standard/StandardMysqlReadWriteSplittingTest.java
Add Hikari tests for the read-write splitting plugin
Also added read-write splitting tests for the following connection strings:
- Initial connection to reader cluster
- Initial connection to reader instance via IP address  
@karenc-bq 
@sergiyv-bitquill
> Add Hikari tests for the read-write splitting plugin

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareWriterFailoverHandler.java
- src/test/java/testsuite/integration/container/AuroraMysqlFailoverIntegrationTest.java
Fix bug where failoverTimeoutMs was not obeyed
- Before this commit, failover could take up to two times the length of
failoverTimeoutMs before giving up. This commit adds changes to
limit failover to run for a maximum of failoverTimeoutMs
milliseconds
@karenc-bq 
@sergiyv-bitquill
> Fix bug where failoverTimeoutMs was not obeyed

- src/test/java/testsuite/integration/container/AuroraMysqlFailoverIntegrationTest.java
Fix bug in test_failoverTimeoutMs
A bug in test_failoverTimeoutMs was making this test non-deterministic. This commit fixes the bug so that test_failoverTimeoutMs passes.
> Fix bug in test_failoverTimeoutMs

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/AWSSecretsManagerPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/AWSSecretsManagerPluginTest.java
Unwrap nested exceptions in AWS Secrets Manager Plugin when checking if the error is caused by invalid credentials
@sergiyvamz
> fix: unwrap nested exceptions in AWS Secrets Manager Plugin when checking if the error is caused by invalid credentials

- src/main/user-api/java/com/mysql/cj/jdbc/JdbcConnection.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ConnectionImpl.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ConnectionWrapper.java
- src/main/user-impl/java/com/mysql/cj/jdbc/MysqlXAConnection.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/MultiHostMySQLConnection.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
Keep track of the connection's XA transaction state to avoid querying for topology during the `PREPARED` state.
#292 
@sergiyvamz
> feat: track whether the connection is currently in a prepared transaction state

- src/main/core-api/java/com/mysql/cj/conf/PropertyDefinitions.java
- src/main/core-api/java/com/mysql/cj/conf/PropertyKey.java
- src/main/resources/com/mysql/cj/LocalizedErrorMessages.properties
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareReaderFailoverHandler.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareReaderFailoverHandlerTest.java
Add enableFailoverStrictReader parameter so the driver only failovers to reader nodes.
@sergiyvamz 
@congoamz
> feat: add enableFailoverStrictReader parameter

- src/main/resources/com/mysql/cj/LocalizedErrorMessages.properties
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareWriterFailoverHandler.java
fix: update topology and check current node role after writer failover
- ensure writer failover does not reconnect to a reader node due to stale topology
@congoamz 
@sergiyvamz
> fix: update topology and check current node role after writer failover

- build.gradle.kts
Remove the SNAPSHOT string from the versioning
`DatabaseMetaData#getDriverVersion` returns the full product name and version with "SNAPSHOT" attached, e.g. `aws-mysql-connector-java-1.1.2-SNAPSHOT` 
Remove the SNAPSHOT string from the versioning.
Addresses #318 
@aaron-congo 
@hsuamz
> chore: remove SNAPSHOT from the full version

- build.gradle.kts
Fix versioning not appearing in the final JAR file.
https://github.com/awslabs/aws-mysql-jdbc/actions/runs/3651103166/jobs/6167915405
The built JARs are unable to pick up the versioning, they are built as `aws-mysql-jdbc.jar` instead of the expected `aws-mysql-jdbc-1.1.2.jar`
@congoamz 
@sergiyvamz
> fix: versioning not being picked up during build

- README.md
In https://github.com/awslabs/aws-mysql-jdbc/pull/34 it looks like the driver name was changed to `software.aws.rds.jdbc.mysql.Driver`. The current readme still suggests the old driver name even though this change now looks to be live.
Readme has been updated with the current driver name.
> Update driver name in readme.

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
Addresses some issues regarding using stale topology and connecting switching 
Changed the criteria for updateTopologyAndConnectIfNeeded() and shouldExceptionTriggerConnectionSwitch() to not rely on isFailoverEnabled() since it may be using a stale host list.
@sergiyv-improving @karenc-bq
> Fix - updating topology and connection switching to not use stale data

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/Monitor.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/MonitorConnectionContext.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPlugin.java
- This PR changes some EFM variables to thread-safe variants. The variables changed are shared between the main thread and the EFM monitoring thread
> Make shared EFM variables thread-safe

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/AWSSecretsManagerPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/AWSSecretsManagerPluginTest.java
Close AWS Secrets Manager Client on connection close or abort. This prevents the leaking org.apache.http.impl.conn.PoolingHttpClientConnectionManager issue described in #343 
AWSSecretsManagerPlugin creates a new SecretsManagerClient for each connection, which creates a new PoolingHttpClientConnectionManager. The driver never closes these SecretsManagerClient so as the user application runs on the number of PoolingHttpClientConnectionManager instances just keep climbing.
Before the fix:
After the fix:
This issue is not applicable in the IAM Authentication plugin.
@aaronchung-bitquill 
@joyc-bq
> fix: close secrets manager client on connection close or abort

- .github/workflows/main.yml
- src/main/core-api/java/com/mysql/cj/util/CacheMap.java
- src/main/resources/com/mysql/cj/LocalizedErrorMessages.properties
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/DefaultMonitorService.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/Monitor.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/MonitorConnectionContext.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/NodeMonitoringConnectionPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyService.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/DefaultMonitorServiceTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/MonitorConnectionContextTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/MonitorTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/MultiThreadedDefaultMonitorServiceTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyServiceTest.java
- src/test/java/testsuite/integration/container/AuroraMysqlFailoverIntegrationTest.java
Optimize thread locks and expiring cache for Enhanced Monitoring plugin.
- Expiring cache object has been replaced with CacheMap<>
- AuroraTopologyService uses multiple caches that provides a better performance and concurrency.
- Optimized work with monitoring context in Enhanced Monitoring plugin. A single queue with monitoring context is replaced with a two separate queues. The first queue holds all active context. When context monitoring time comes, the context is relocated to the second queue. Separating queues help to clear identify context that requires active node monitoring.
- Performance optimization for various part of the code.
@karenc-bq 
@congoamz
> Optimize thread locks and expiring cache for Enhanced Monitoring plugin

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
Check log level before logTrace and logDebug with Messages.getString(…) and allocating argument arrays for String formatting. 
This avoids loading the messages from the resourcebundle and the subsequent String formatting and saves some unnecessary allocations when the log level is not debug nor trace (in the common case)
The primary reason for the change was the logTrace statement in the performSpecialMethodHandlingIfRequired method which can be called often, as it was in our case (it showed up in the allocation profile). The other log statements are usually called less frequently, but I added the check there too for consistency.
> Check log level before logTrace and logDebug with Messages.getString(…)

- src/main/user-impl/java/com/mysql/cj/jdbc/ConnectionImpl.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/BestResponseTimeBalanceStrategy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/RandomBalanceStrategy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/SequentialBalanceStrategy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ServerAffinityStrategy.java
The driver sometimes wrap the JdbcConnection object into a proxy. Some methods will attempt to explicitly cast the JdbcConnection object into a MySQL ConnectionImpl object. This will throw a ClassCastException.
For all JDBC methods that pass in a JdbcConnection as a parameter, check if the object can be casted into a ConnectionImpl object directly, if not, use `unwrap` instead of cast.
@joyc-bq @aaronchung-bitquill @brunos-bq
> fix: class cast exception on proxy objects

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/AWSSecretsManagerPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/AWSSecretsManagerPluginTest.java
fix: AWSSecretsManagerPlugin to update ConnectionProxy HostInfo on openInitialConnection (#361)
Plugins use the currentHostInfo from ConnectionProxy to create connections. Unfortunately, it doesnt get updated with credentials by AWSSecretsManagerPlugin, so connections made this way result in access denials. 
Changed AWSSecretsManagerPlugin to update the currentHostInfo of the CurrentConnectionProvider with user/password so that subsequent plugins that use for creating connections won't get "access denied". 
After talking with @sergiyv-improving , also disabled the code in FailoverConnectionPlugin in attemptConnectionUsingCachedTopology() method as it does not work with the AWSSecretsManagerPlugin, and has no proven improved performance benefits. 
@sergiyv-improving @karenc-bq @aaron-congo …
> fix: AWSSecretsManagerPlugin to update ConnectionProxy HostInfo on openInitialConnection (#361)

- README.md
Update links to Maven central to point to Sonatype.
See also: https://central.sonatype.org/faq/what-happened-to-search-maven-org/
> Update links to Maven central in README.md

- src/main/core-api/java/com/mysql/cj/util/Util.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
Instead of calling `containsKey` then calling `get`, which requires looking up the map twice, simply call get and check the value. This works because the map doesn't store null values.
@brunos-bq
@aaronchung-bitquill
> refactor: reduce map lookups to reduce number of locks required

- CHANGELOG.md
@karenc-bq @joyc-bq  @sergiyv-improving @aaron-congo @brunos-bq
> chore: Update changelog for v1.1.5

- src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaDataUsingInfoSchema.java
Resource shutdown/release for DatabaseMetaDataUsingInfoSchema.java
One ResultSet instance was not being closed, and was put into a try with resources block. Other try-catch blocks were also altered to be try with resources blocks.
> refactor: resource shutdown/release for DatabaseMetaDataUsingInfoSchema.java

- src/main/user-impl/java/com/mysql/cj/jdbc/CallableStatement.java
Resource shutdown/release for CallableStatement.java
One ResultSet instance was not being closed, and was put into a try with resources block. Other try-catch blocks were also altered to be try with resources blocks.
> refactor: resource shutdown/release for CallableStatement.java

- src/main/user-impl/java/com/mysql/cj/jdbc/PreparedStatementWrapper.java
If the driver wraps a Statement in a proxy, it needs to be unwrapped before it can be cast to a ClientPreparedStatement. A class cast exception will be thrown if the statement object isn't unwrapped.
Addresses issue #401
Checks to confirm if a statement is an instance of a ClientPreparedStatement have been added to methods that cast `this.wrapperStmt` to a ClientPreparedStatement inside `PreparedStatementWrapper.java`.
> fix: unwrap statement if it is not a ClientPreparedStatement

- src/main/core-api/java/com/mysql/cj/conf/HostInfo.java
- src/main/resources/com/mysql/cj/LocalizedErrorMessages.properties
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyService.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ITopologyService.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyServiceTest.java
Remove the isMultiWriterCluster flag from the AuroraTopologyService
Multi writer clusters are not longer supported, so the isMultiWriterCluster flag that was used to disable failover has been removed. Additionally, checks have been added to ensure stale writer records that are obtained post writer-failover are not being used.
> Remove the isMultiWriterCluster flag from the AuroraTopologyService

- src/main/resources/com/mysql/cj/LocalizedErrorMessages.properties
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionUtils.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyService.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareReaderFailoverHandler.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareWriterFailoverHandler.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareReaderFailoverHandlerTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareTestUtils.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareWriterFailoverHandlerTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java
Remove additional host properties from topology
When the failover plugin is initialized, it passes properties to the AuroraTopologyService. This means that when the topology service gets a topology, every HostInfo object in the topology will contain the same properties. The topology is stored in a cache, which is identified by the cluster ID. This means different connections to the same cluster may retrieve topology information containing properties of each other.
This PR removes the host properties other than the host and port number from the topology service and instead sets the initialConnectionProps to contain them instead.
Addresses issue #407 
@YoungHu
> refactor: remove host properties from topology

- CHANGELOG.md
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java
- src/test/java/com/mysql/cj/jdbc/ha/ConnectionProxyTest.java
Accept "convertToNull" value for property "zeroDateTimeBehaviour"
Some connection properties such as `zeroDateTimeBehaviour` are altered in the `fixHostInfo` method. The `zeroDateTimeBehaviour` value in particular is replaced in the `replaceLegacyPropertyValues` method. This allows the driver to accept both upper and lowercase values. When the driver detects an AWS JDBC Driver protocol, it will create a proxy using the properties the user specified and not the corrected set. This PR will use the "fixed" properties instead.
> fix: Accept "convertToNull" value for property "zeroDateTimeBehaviour"

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
`updateHostIndex` may throw an IndexOutOfBoundException if `this.currentHostIndex` is -1.
Addresses sissue #417
> fix: handle the case when this.currentHostIndex is an invalid index

- src/main/resources/com/mysql/cj/LocalizedErrorMessages.properties
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionUtils.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareReaderFailoverHandlerTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareTestUtils.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareWriterFailoverHandlerTest.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java
- src/test/java/com/mysql/cj/util/ConnectionUtilsTest.java
Keep connection properties in connection URL when creating new hosts after failover
When new hostInfo objects were made post-failover, the ConnectionUrl object was missing connection properties, leading to inaccurate metadata.
Adresses https://github.com/awslabs/aws-mysql-jdbc/issues/407#issuecomment-1589188945
> fix: keep connection properties in connection URL when creating new hosts after failover

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPluginTest.java
Ensure the failover plugin initial properties contain updated values from previous plugins
After the changes in #410, the Failover plugin was missing any connection property changes that were made when `openInitialConnection` was called in plugins earlier in the plugin chain, such the the AWS Secrets Manager plugin. This PR updates the initial connection properties based on the ConnectionUrl provided by the previous plugin in the plugin chain.
> fix: ensure the failover plugin initial properties contain updated values from previous plugins

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/AuroraTopologyService.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
Check the global transaction state before querying the topology
> fix: avoid updating topology during a global transaction

- src/main/core-impl/java/com/mysql/cj/ServerPreparedQuery.java
Addresses #422 
Port over fix from https://github.com/mysql/mysql-connector-j/pull/97
> fix: redundant reset statement called due to incorrect condition

- CHANGELOG.md
- src/main/user-impl/java/com/mysql/cj/jdbc/StatementImpl.java
- src/test/java/testsuite/regression/StatementRegressionTest.java
fix: add check to prevent updateCounts being set to an invalid number
When an error occurs on executing a batch statement while `allowMultiQueries` is set to true, the updateCounts is incorrectly set to -1 when it should be left as -3 (`Statement.EXECUTE_FAILED`). This PR adds a check to ensure this does not happen.
Addresses #450.
> fix: add check to prevent updateCounts being set to an invalid number

- src/main/user-impl/java/com/mysql/cj/jdbc/StatementImpl.java
- src/test/java/testsuite/regression/StatementRegressionTest.java
Batch execute with comments results in error
Batch execute with comments resulted in errors about being unable to issue statements that produce result sets. The `isNonResultSetProducingQuery` method was missing the `None` query return type.
Addresses #464
> fix: batch execute with comments results in error

- README.md
- src/main/core-impl/java/com/mysql/cj/NativeSession.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/FailoverConnectionProxy.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/AWSSecretsManagerPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/DefaultConnectionPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ReaderClusterConnectionPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/ReaderClusterConnectionPluginFactory.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareReaderFailoverHandler.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareWriterFailoverHandler.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/plugins/failover/FailoverConnectionPlugin.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/util/ConnectionUtils.java
- src/main/user-impl/java/com/mysql/cj/jdbc/ha/util/RdsUtils.java
- src/main/user-impl/java/com/mysql/cj/jdbc/integration/c3p0/MysqlConnectionTester.java
- src/test/java/com/mysql/cj/jdbc/ha/plugins/failover/ClusterAwareTestUtils.java
- src/test/java/com/mysql/cj/util/ConnectionUtilsTest.java
- src/test/java/testsuite/integration/container/AuroraMysqlIntegrationTest.java
fix: query timeout kill query directed to incorrect instance
When a query timeout is set and the timeout value has passed, the driver sends a kill query to stop the process through a new connection that was created using the same host as the original connection. When using the reader cluster url, connections are randomly sent to one of the available reader instances. This will occasionally cause errors when the kill query is sent to a different instance where the statement was not executed, resulting in an "Unknown process id" message.
This PR adds a check in the default connection plugin for connections using the reader cluster url. Once the connection is made using the reader cluster url, a new connection is made to a reader instance that is obtained by querying for the current instance …
> fix: query timeout kill query directed to incorrect instance

- src/main/user-impl/java/com/mysql/cj/jdbc/StatementImpl.java
- src/test/java/testsuite/regression/StatementRegressionTest.java
When batch statements are executed, followed by individual statements, the generated keys will be for the batch statements.  This PR allows the generated keys for the statement to be for the latest statement execution.
Addresses #484
> fix: incorrect generated keys after batch and individual statement executions

- src/test/java/testsuite/integration/utility/ContainerHelper.java
update mysql docker container image to 8.0.36
update mysql docker container image to 8.0.36
> update mysql docker container image to 8.0.36

- src/main/user-impl/java/com/mysql/cj/jdbc/ha/ConnectionProxy.java
- src/test/java/testsuite/integration/container/AuroraMysqlIntegrationTest.java
Fix statement.cancel() waiting for statement to finish
When a long running query is executed and `statement.cancel()` is used to stop it, the driver will not immediately cancel the statement and will wait for it to finish instead. This PR replaces the synchronized block with a ReentrantLock.
Addresses #527
> fix: statement.cancel() waits for statement to finish

- README.md
Link for the build badge is outdated
> fix: build status badge not properly rendered due to outdated link

- build.gradle.kts
- src/build/misc/pom.xml
Bump com.google.protobuf:protobuf-java from 3.21.9 to 3.25.5
@karenc-bq
> Bump com.google.protobuf:protobuf-java from 3.21.9 to 3.25.5
